const USERS_KEY='app_users';
const CURRENT_KEY='current_user';
const getUsers=():any[]=>{try{return JSON.parse(localStorage.getItem(USERS_KEY)||'[]')}catch{return[]}};
const saveUsers=(u:any[])=>localStorage.setItem(USERS_KEY,JSON.stringify(u));
export const getUserByPhone=async(p:string)=>getUsers().find(u=>u.phone===p)||null;
export const getUserByReferralCode=async(c:string)=>getUsers().find(u=>u.referralCode===c.toUpperCase())||null;
export const createUser=async(u:any)=>{const a=getUsers();a.push(u);saveUsers(a);return u;};
export const setCurrentUser=(u:any)=>localStorage.setItem(CURRENT_KEY,JSON.stringify(u));
export const getCurrentUser=()=>{try{return JSON.parse(localStorage.getItem(CURRENT_KEY)||'null')}catch{return null}};
export const addNotification=async(n:any)=>n;
export const getUserById=async(id:string)=>getUsers().find(u=>u.id===id)||null;
export const getUsers=async()=>getUsers();
export const getProducts=async()=>[];
export const getUserProducts=async()=>[];
export const createProduct=async()=>{};
export const updateProduct=async()=>{};
export const getRecharges=async()=>[];
export const createRecharge=async()=>{};
export const updateRecharge=async()=>{};
export const getWithdrawals=async()=>[];
export const createWithdrawal=async()=>{};
export const updateWithdrawal=async()=>{};
export const getWallets=async()=>[];
export const saveWallet=async()=>{};
export const getNotifications=async()=>[];
export const getUserNotifications=async()=>[];
export const markNotificationRead=async()=>{};
export const getRedeemCodes=async()=>[];
export const createRedeemCode=async()=>{};
export const updateRedeemCode=async()=>{};
export const updateUser=async(id:string,updates:any)=>{const a=getUsers();const i=a.findIndex(u=>u.id===id);if(i>=0){a[i]={...a[i],...updates};saveUsers(a);setCurrentUser(a[i])}};
export const deleteUserById=async()=>{};
export const deleteProduct=async()=>{};
export const deleteWalletsByUser=async()=>{};
export const deleteNotificationsByUser=async()=>{};
export const deleteRedeemCodeById=async()=>{};
export const getUserRecharges=async()=>[];
export const getUserWithdrawals=async()=>[];
export const getUserWallets=async()=>[];
export const refreshCurrentUser=async()=>getCurrentUser();
export const getAdminSession=()=>localStorage.getItem('admin')==='true';
export const setAdminSession=(v:boolean)=>v?localStorage.setItem('admin','true'):localStorage.removeItem('admin');
export const processDailyIncome=async()=>({processed:0,totalPaid:0,expired:0,skipped:0});
export const runDailyIncomeWithStats=async()=>({processed:0,totalPaid:0,expired:0,skipped:0});
